<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Work</name>
   <tag></tag>
   <elementGuidId>5fa78de0-cb04-48af-829e-54e78278b4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/nav/div/div[3]/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-item.without-custom-cursor.body.small-size.bold-weight.uppercase.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c577cd8-c475-45c4-ba78-44158cc4f058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slug</name>
      <type>Main</type>
      <value>work</value>
      <webElementGuid>7eab9d23-b466-4373-a812-556fccd1d4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>346ac2b0-32e9-4fba-805f-bb4cc66f67c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/work</value>
      <webElementGuid>c0e13729-76c3-4765-8de2-a49164c98948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item without-custom-cursor body small-size bold-weight uppercase active</value>
      <webElementGuid>33a2a710-4f85-41cb-833b-d7c06ffca44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Work
            </value>
      <webElementGuid>5f938e0a-7343-489c-93b9-5b1b974ab82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/nav[1]/div[@class=&quot;show-for-large navigation loaded is-homepage bg-dark&quot;]/div[@class=&quot;grid-x nav-items-container&quot;]/div[@class=&quot;col large-8 menu-nav-items active&quot;]/div[1]/div[@class=&quot;nav-items&quot;]/a[@class=&quot;menu-item without-custom-cursor body small-size bold-weight uppercase active&quot;]</value>
      <webElementGuid>2de303dd-e917-4438-abc3-5020f3243940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/nav/div/div[3]/div[2]/div/div/a</value>
      <webElementGuid>5972af19-0a80-40aa-8b19-8166fdd4ad17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Work')]</value>
      <webElementGuid>156ad18a-6607-4cc2-8fc4-f85a54d7f9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butchershop'])[1]/following::a[1]</value>
      <webElementGuid>60f4d7ae-76f3-4aba-9a17-007ecac10adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEAT FAILURE REPORT 2022'])[2]/following::a[2]</value>
      <webElementGuid>f47f8655-0f4a-4075-950f-c4dc9e268423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[1]</value>
      <webElementGuid>502cc5dd-2857-4ef6-80d1-317e9a0d43f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beat Failure'])[1]/preceding::a[2]</value>
      <webElementGuid>f69f7154-980a-48f6-b23a-31897117b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work']/parent::*</value>
      <webElementGuid>079b9db1-c938-4491-898e-cb99011270f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/work')]</value>
      <webElementGuid>20b1f388-962c-4838-a68c-dfe67dd624eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/a</value>
      <webElementGuid>24c450e4-9a6b-4de1-890b-8f15fecac990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/work' and (text() = '
            Work
            ' or . = '
            Work
            ')]</value>
      <webElementGuid>4f1f18f6-d973-4531-9155-7e351e0bc4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
