<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cookies_banner</name>
   <tag></tag>
   <elementGuidId>771ef73c-d6a0-4b9c-a95f-8beb55c36e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cookie-banner.display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3c5b23c-2f2c-443a-99c9-794c66d95ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-banner display</value>
      <webElementGuid>4fdc1b7d-30ab-41ae-a498-08ba1d87d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This website uses cookies to improve your experience. We’ll assume you’re ok with this, but you can opt-out if you wish. Accept Reject</value>
      <webElementGuid>68b2104f-5326-4591-b031-555dda30f1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;cookie-banner display&quot;]</value>
      <webElementGuid>28d89b78-ccfd-4856-8ef6-52286a1bf819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[3]</value>
      <webElementGuid>7a5705b4-a8d7-4a5a-892f-e159e6799ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Services &amp; Privacy Policy'])[1]/following::div[5]</value>
      <webElementGuid>3b19a22e-cae4-491e-b49d-72602f0fc9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clutch'])[1]/following::div[5]</value>
      <webElementGuid>d0912a16-f61e-4f77-b174-da041d6965c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>6d2fac10-bcb5-440c-b219-99938d9c55cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This website uses cookies to improve your experience. We’ll assume you’re ok with this, but you can opt-out if you wish. Accept Reject' or . = 'This website uses cookies to improve your experience. We’ll assume you’re ok with this, but you can opt-out if you wish. Accept Reject')]</value>
      <webElementGuid>47f62b1b-cbe3-454d-a3fb-812133969fdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
