<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_no_full_screen</name>
   <tag></tag>
   <elementGuidId>bb717a48-6b22-41b9-93da-9236afb61f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.video-preview.with-custom-cursor.cursor-by-progress-scroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/section/div/div[2]/div/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>fc742bda-14eb-4164-a0c3-0638cb9db183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>metadata</value>
      <webElementGuid>ab31b1ed-1b8e-43cc-be6b-3f50c32fa299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>watch</value>
      <webElementGuid>30fe016f-f86b-4bc2-a880-6850ea1577bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoplay</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>a31802f2-7798-4c23-abaf-e176d21ba25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>muted</name>
      <type>Main</type>
      <value>muted</value>
      <webElementGuid>e127a25b-18fc-4da6-b20c-16eb193aaa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loop</name>
      <type>Main</type>
      <value>loop</value>
      <webElementGuid>82b1fd8e-f9da-4480-9a4a-7299cce03125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>/assets/hero-video-preview-image-1674579414.jpg</value>
      <webElementGuid>39795081-9807-4e20-a7d6-888524bfa881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/bc-reel-10sec-web-desktop-FINAL.mp4</value>
      <webElementGuid>832aae9e-0031-4e71-a308-0a031c45b948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-preview with-custom-cursor cursor-by-progress-scroll</value>
      <webElementGuid>625f277a-9e5d-4d06-bdb1-160f3e992a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Your browser does not support the video tag.
            </value>
      <webElementGuid>8bc06acd-1d0b-4a44-a21a-6627b73e107a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/section[@class=&quot;hero&quot;]/div[1]/div[2]/div[@class=&quot;pin-spacer&quot;]/div[@class=&quot;h-screen&quot;]/video[@class=&quot;video-preview with-custom-cursor cursor-by-progress-scroll&quot;]</value>
      <webElementGuid>a3cf7f18-77d4-44db-98ea-f8373c4296a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/section/div/div[2]/div/div/video</value>
      <webElementGuid>da3e55b4-d4f7-44db-9440-3dbad8a45978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[1]/following::video[1]</value>
      <webElementGuid>a2655b7d-d20b-4dd8-b761-f5ec0d23192f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support the video tag.'])[1]/following::video[1]</value>
      <webElementGuid>3dda8f26-1d3d-4fa9-a21d-6c8d285546e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titleas'])[1]/preceding::video[1]</value>
      <webElementGuid>24fea95a-885d-4577-9c8e-2e9ff8fc49e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='– Butchershop® Global is a'])[1]/preceding::video[1]</value>
      <webElementGuid>ff2e30fe-caab-43eb-b2d9-b24a0631a337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/video</value>
      <webElementGuid>e65b9698-d852-48fd-b6ab-a58c8b13cef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = '/assets/bc-reel-10sec-web-desktop-FINAL.mp4' and (text() = '
                Your browser does not support the video tag.
            ' or . = '
                Your browser does not support the video tag.
            ')]</value>
      <webElementGuid>a052bf38-ac8b-48ab-a89a-58f386074b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
