<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_full_screen</name>
   <tag></tag>
   <elementGuidId>b1e6a224-f0cd-43e1-910c-df13eefe45b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vjs_video_3_html5_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='vjs_video_3_html5_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>22a0e7ef-912a-4fd6-b04b-33e1c257464a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>exit</value>
      <webElementGuid>4efbb857-0387-4f83-b23a-3283c8250520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>metadata</value>
      <webElementGuid>fb77143e-6273-4c7c-92a5-37f94162b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>/assets/hero-video-preview-image-1674579414.jpg</value>
      <webElementGuid>2b89d184-5fd3-4e00-8c12-08b82dc65c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>33ac1f99-5172-49c2-8610-a60a27fde3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vjs_video_3_html5_api</value>
      <webElementGuid>370e70de-093e-47c1-b0e2-fd5970fc3e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2e0e6fa0-db1b-4d78-9c7c-804c2d9d1e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value> /assets/bc-reel-full_FINAL.mp4</value>
      <webElementGuid>54370460-0959-40b8-97fa-d3a3931742b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Your browser does not support the video tag.
        </value>
      <webElementGuid>436ccedf-e339-4db5-b9e8-0a776a7387d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vjs_video_3_html5_api&quot;)</value>
      <webElementGuid>8e174bef-335e-401a-9e79-fa6a0762f6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='vjs_video_3_html5_api']</value>
      <webElementGuid>dfff7157-4ff1-456b-9c8f-dbf14fa45d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vjs_video_3']/video</value>
      <webElementGuid>3198de80-3262-49ad-9940-6988333c6e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::video[1]</value>
      <webElementGuid>a7db8728-0bb4-4ece-82ba-9c095a27b8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lets Talk'])[2]/following::video[1]</value>
      <webElementGuid>25c47856-6df8-4a3d-943f-b9abfc999cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Player is loading.'])[1]/preceding::video[1]</value>
      <webElementGuid>6b1018fa-4a10-46ec-a0f5-a1511f53925c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play Video'])[1]/preceding::video[1]</value>
      <webElementGuid>89544d85-4f55-4066-8c2c-fbf18422194b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your browser does not support the video tag.']/parent::*</value>
      <webElementGuid>ccef8c37-8185-4b89-9d45-90252792cbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>3e803918-5389-4bc9-95d7-16d01b78af7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'vjs_video_3_html5_api' and @src = ' /assets/bc-reel-full_FINAL.mp4' and (text() = '
            Your browser does not support the video tag.
        ' or . = '
            Your browser does not support the video tag.
        ')]</value>
      <webElementGuid>fa811154-1299-4a99-88ea-1cb2c329faba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
