<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Your browser does not support the video tag</name>
   <tag></tag>
   <elementGuidId>ab02b8ab-f9d1-4cd4-9000-51144e2d5e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.video-preview.with-custom-cursor.cursor-by-progress-scroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/section/div/div[2]/div/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>bd1f45ca-e846-4fd8-89f7-efd15826a418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>metadata</value>
      <webElementGuid>77968b1d-bd26-4368-8145-4dd6e8d25be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>watch</value>
      <webElementGuid>60be9570-577e-4004-97d5-d7e2dd77b6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoplay</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>2636e343-68d9-4081-8bc2-19e9fce6fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>muted</name>
      <type>Main</type>
      <value>muted</value>
      <webElementGuid>66eaadb3-7a33-4810-86fe-f8c8151de9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loop</name>
      <type>Main</type>
      <value>loop</value>
      <webElementGuid>d571d5d5-b013-43e5-ac78-bc95707a5de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>/assets/hero-video-preview-image-1674579414.jpg</value>
      <webElementGuid>1d4459f4-00ca-4aad-b86d-fd6e87d2b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/bc-reel-10sec-web-desktop-FINAL.mp4</value>
      <webElementGuid>5b681ebc-8075-446b-a695-0b3882f1b69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-preview with-custom-cursor cursor-by-progress-scroll</value>
      <webElementGuid>01d20a42-5de6-4b65-892d-14513b59eda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Your browser does not support the video tag.
            </value>
      <webElementGuid>9231302d-b520-4032-8792-f8a21f50924d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/section[@class=&quot;hero&quot;]/div[1]/div[2]/div[@class=&quot;pin-spacer&quot;]/div[@class=&quot;h-screen&quot;]/video[@class=&quot;video-preview with-custom-cursor cursor-by-progress-scroll&quot;]</value>
      <webElementGuid>435dffa3-c5c8-4ede-a6ee-0c42fb7f7a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/section/div/div[2]/div/div/video</value>
      <webElementGuid>bdd28573-e571-4ec4-b449-99111750c35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[1]/following::video[1]</value>
      <webElementGuid>05863a23-1cf7-41d1-966d-b31137efa9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support the video tag.'])[1]/following::video[1]</value>
      <webElementGuid>ce61653e-bea8-4b38-9fcd-615b9cecd9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titleas'])[1]/preceding::video[1]</value>
      <webElementGuid>2273967b-a4bf-4051-b889-92101caa1f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='– Butchershop® Global is a'])[1]/preceding::video[1]</value>
      <webElementGuid>f78c2699-0b75-44f9-811b-d63a3ddbc63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/video</value>
      <webElementGuid>4da16bf5-c86d-4649-b5f4-b766b7718f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = '/assets/bc-reel-10sec-web-desktop-FINAL.mp4' and (text() = '
                Your browser does not support the video tag.
            ' or . = '
                Your browser does not support the video tag.
            ')]</value>
      <webElementGuid>d49c0e63-e285-4915-99b8-ec0aced81381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
